// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/a8m/entspatial/ent/runtime.go

const (
	Version = "v0.7.1-0.20210407065344-2cc1c628dc42"            // Version of ent codegen.
	Sum     = "h1:l+Y+yZkNutWmj5d/ql0i1PA2ZyQXY/i/vR2EbHZeFLE=" // Sum of ent codegen.
)
